In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
import seaborn as sns
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
from sklearn.linear_model import Perceptron


In [23]:
df = pd.read_csv("amazon_musical_instruments_reviews.csv")

In [24]:
df.head()


,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,A2IBPI20UZIR0U,1384719342,"cassandra tu ""Yeah, well, that's just like, u...","[0, 0]","Not much to write about here, but it does exac...",5.0,good,1393545600,"02 28, 2014"
1,A14VAT5EAX3D9S,1384719342,Jake,"[13, 14]",The product does exactly as it should and is q...,5.0,Jake,1363392000,"03 16, 2013"
2,A195EZSQDW3E21,1384719342,"Rick Bennette ""Rick Bennette""","[1, 1]",The primary job of this device is to block the...,5.0,It Does The Job Well,1377648000,"08 28, 2013"
3,A2C00NNG1ZQQG2,1384719342,"RustyBill ""Sunday Rocker""","[0, 0]",Nice windscreen protects my MXL mic and preven...,5.0,GOOD WINDSCREEN FOR THE MONEY,1392336000,"02 14, 2014"
4,A94QU4C90B1AX,1384719342,SEAN MASLANKA,"[0, 0]",This pop filter is great. It looks and perform...,5.0,No more pops when I record my vocals.,1392940800,"02 21, 2014"


In [25]:
df['overall'].value_counts

<bound method IndexOpsMixin.value_counts of 0        5.0
1        5.0
2        5.0
3        5.0
4        5.0
        ... 
10256    5.0
10257    5.0
10258    4.0
10259    4.0
10260    4.0
Name: overall, Length: 10261, dtype: float64>

In [26]:
df.isna().sum()

reviewerID         0
asin               0
reviewerName      27
helpful            0
reviewText         7
overall            0
summary            0
unixReviewTime     0
reviewTime         0
dtype: int64

In [27]:
df=df.dropna(subset=['reviewerName'])

In [28]:
df=df.dropna(subset=['reviewText'])

In [29]:
df.isna().sum()

reviewerID        0
asin              0
reviewerName      0
helpful           0
reviewText        0
overall           0
summary           0
unixReviewTime    0
reviewTime        0
dtype: int64

In [30]:
x=df['reviewText']
y=df['overall']


vectorizer=CountVectorizer()
x=vectorizer.fit_transform(x)

joblib.dump(vectorizer,"amazon_musical_instruments_reviews.pkl")


['amazon_musical_instruments_reviews.pkl']

In [31]:
from imblearn.over_sampling import SMOTE
smote=SMOTE()
x,y=smote.fit_resample(x,y)

In [32]:
y.value_counts()

overall
5.0    6912
3.0    6912
4.0    6912
2.0    6912
1.0    6912
Name: count, dtype: int64

In [34]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=42)


In [41]:
model=Perceptron()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)
print(y_pred)   
joblib.dump(model,"model_amazon_musical_instruments_reviews.pkl")



[4. 2. 3. ... 1. 1. 5.]


['model_amazon_musical_instruments_reviews.pkl']

In [40]:

print(confusion_matrix(y_test,y_pred))

#Detailed classification report 
print("\nClassification Report: ")
print(classification_report(y_test,y_pred))

[[1517   27   89   96   14]
 [ 153 1215  194  125   32]
 [ 149  160 1021  283  100]
 [  92  136  240  945  326]
 [  13   23   66  241 1383]]

Classification Report: 
              precision    recall  f1-score   support

         1.0       0.79      0.87      0.83      1743
         2.0       0.78      0.71      0.74      1719
         3.0       0.63      0.60      0.61      1713
         4.0       0.56      0.54      0.55      1739
         5.0       0.75      0.80      0.77      1726

    accuracy                           0.70      8640
   macro avg       0.70      0.70      0.70      8640
weighted avg       0.70      0.70      0.70      8640

