In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [28]:
import numpy as np

In [29]:

import time
a=list(range(1000000))
b=list(range(1000000))

start = time.time()
result = [x + y for x, y in zip(a, b)]
end = time.time()
print("Python List Time:",end - start)

Python List Time: 0.31380248069763184


In [30]:
a_np=np.arange(1000000)
b_np=np.arange(1000000)
start = time.time()
result_np = a_np+b_np
end = time.time()
print("Numpy Array TIME:",end - start)

Numpy Array TIME: 0.003008127212524414


In [31]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b
print(c)

[5 7 9]


In [32]:
a = np.array([1,2,3])
b = 2
c = a*b
print(c)

[2 4 6]


In [33]:
a = np.array([1,2,3,4,5])
print("1D Arary:a",a)

1D Arary:a [1 2 3 4 5]


In [34]:
#1D array
a = np.array([1,2,3,4,5])
print("1D Arary:a",a)
a.ndim

1D Arary:a [1 2 3 4 5]


1

In [35]:
#2D array
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n2D Arary:\n ",b)
b.ndim




2D Arary:
  [[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [36]:
c = np.array([[[1,2,3],[2,3,4],[3,4,5]], [[4,5,6],[5,6,7],[6,7,8]]])
print("\n3D Array:\n", c)
c.ndim


3D Array:
 [[[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]
  [6 7 8]]]


3

In [37]:
zeros=np.zeros((2,3))
ones=np.ones((3,2))
arange=np.arange(0,10,2)
linspace=np.linspace(0,1,5)

print("\n Zeros:\n",zeros)
print("\n Ones:\n",ones)
print("\n Arange:\n",arange)
print("\n linspace:\n",linspace)


 Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

 Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

 Arange:
 [0 2 4 6 8]

 linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [39]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Element at row 1 ,col 2:",arr[0,1])

Element at row 1 ,col 2: 20


In [42]:
print("\nFrist two rows:\n",arr[:2])
print("\nLast column:\n",arr[:,-1])
print("\n Elements > 50:\n",arr[arr>50])



Frist two rows:
 [[10 20 30]
 [40 50 60]]

Last column:
 [30 60 90]

 Elements > 50:
 [60 70 80 90]


In [43]:
x =  np.array([1,2,3])
y = np.array([4,5,6])
print("Addition:",x+y)
print("Multiplication:",x*y)
print("scalar Mulyiplication:",x*10)

Addition: [5 7 9]
Multiplication: [ 4 10 18]
scalar Mulyiplication: [10 20 30]


In [47]:
A = np.array([[1,2],[3,4]])
B = np.array([[2,0],[1,2]])
print("\nMatrix Multiplication:\n",A @ B)
print("Standard Deviation of x :",np.std(x))
print("Max of y:",np.max(y))
print("Min of y:",np.min(y))


Matrix Multiplication:
 [[ 4  4]
 [10  8]]
Standard Deviation of x : 0.816496580927726
Max of y: 6
Min of y: 4


In [46]:
mat1=np.array([[1,2],
               [3,4]])
mat2=np.array([[2,0],
               [1,2]])
result=np.dot(mat1,mat2)
print("Matrix Multiplication:\n",result)

Matrix Multiplication:
 [[ 4  4]
 [10  8]]


In [49]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[2, 0],
              [1, 2]])


result=np.dot(A,B)
print("Matrix Multiplication:\n",result)

Matrix Multiplication:
 [[ 4  4]
 [10  8]]


In [57]:
arr=np.arange(20)
print(arr)
shaped=arr.shape
print("Shape array:\n",shaped)

reshaped=arr.reshape(4,5)
print("Shape array:\n",reshaped)
flattened=arr.flatten()
print("flatttened:",flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Shape array:
 (20,)
Shape array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
flatttened: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [58]:
a=np.array([[1],[2],[3]])
b=np.array([10,20,30,40])
print("\nBroadcast Addition:\n",a+b)



Broadcast Addition:
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [59]:
a=np.array([[1],[2],[3]])
b=np.array([10,20,30,40])
c=a+b
print("\nBroadcast Addition:\n",a+b)
c[:,-1]



Broadcast Addition:
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


array([41, 42, 43])

In [60]:
a=np.array([[1],[2],[3]])
b=np.array([10,20,30,40])
c=a+b
print("\nBroadcast Addition:\n",a+b)
print(c[1:2,-2])
print(c[1][1])




Broadcast Addition:
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
[32]
22


In [61]:
## Array Data Types (dtype)

arr_int = np.array([1, 2, 3])
print("Data type:", arr_int.dtype)
print("Data type:", type(arr_int))

arr_float = np.array([1.5, 2.6, 3.9])
print("Float dtype:", arr_float.dtype)

# Convert to int
converted = arr_float.astype(int)
print("Converted to int:", converted)

Data type: int32
Data type: <class 'numpy.ndarray'>
Float dtype: float64
Converted to int: [1 2 3]


In [62]:
x = np.array([1,2,3,4])
copy_x=x.copy()
view_x=x.view()
print("Orignal:",x)
print("view:",view_x)
x[0]=99
print("After Change:",x)
print("Copy:",copy_x)
print("View:",view_x)

Orignal: [1 2 3 4]
view: [1 2 3 4]
After Change: [99  2  3  4]
Copy: [1 2 3 4]
View: [99  2  3  4]


view_x = x.view()`

 * Makes a shallow copy (a view):

 * A new array object is created.

 * But it shares the same data buffer as x.

* So any change to the data in x is reflected in view_x.

In [64]:
print(copy_x is x)
print(view_x is x)  

# Check if they share the same data buffer
print(np.shares_memory(x, copy_x))   # False
print(np.shares_memory(x, view_x))

False
False
False
True


Create a 4x4 array with numbers from 1 to 16.
2. Slice out a 2x2 square from the center.
3. Perform element-wise addition and multiplication with another 4x4 array.
4. Convert the original array into float and reshape to (2, 8).
5. Show a working example of broadcasting using arrays of shape (3, 1) and (1, 3).
6. Demonstrate the effect of modifying a view vs modifying a copy.

In [103]:
arr=np.arange(1,17)
reshaped=arr.reshape(4,4)

print("array: \n",reshaped)

slices = reshaped[1:3,1:3]
print("\n2x2 center slice:\n",slices)






array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

2x2 center slice:
 [[ 6  7]
 [10 11]]


In [84]:
arr1=np.arange(1,17)
reshaped1=arr.reshape(4,4)
arr2=np.arange(16,1,-1)
reshaped2=arr.reshape(4,4)


add_result = arr1 + arr2
mul_result = arr1 * arr2
print(add_result)
print(mul_result)


[17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17]
[16 30 42 52 60 66 70 72 72 70 66 60 52 42 30 16]


In [87]:
arr1=np.arange(1,17)
reshaped1=arr.reshape(4,4)
arr=arr1.astype(float)
print(arr)
print(arr.dtype)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
float64


In [90]:
a = np.array([[1], [2], [3]])   
b = np.array([[10, 20, 30]])    
broadcast_result = a + b
print("\nBroadcasting (3,1) + (1,3):\n", broadcast_result)


Broadcasting (3,1) + (1,3):
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [94]:
x = np.array([4,5,6,7])
copy_x=x.copy()
view_x=x.view()
print("Orignal:",x)
print("view:",view_x)
x[0]=34
print("After Change:",x)
print("Copy:",copy_x)
print("View:",view_x)

Orignal: [4 5 6 7]
view: [4 5 6 7]
After Change: [34  5  6  7]
Copy: [4 5 6 7]
View: [34  5  6  7]
